spring:
  profiles:
    active: local
  application:
    name: o-bot
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jwt:
    secret: ${JWT_SECRET}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  override-with-generic-response: false
aws:
  region: ${AWS_REGION}
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  dynamodb:
    endpoint: ${DYNAMO_DB_ENDPOINT}
external:
  gemini:
    api-key: ${GEMINI_API_KEY}
    api-url: ${GEMINI_API_URL}