package com.osolar.obot.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.osolar.obot.config.DynamoDBConfig;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "inquiry")
public class Inquiry {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "byResponseId")
    private String responseId;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDBConfig.LocalDateTimeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    private String input;

    @DynamoDBAttribute
    private String prompt;

    @DynamoDBAttribute
    private String searchResult;

/*-------------------- Constructors --------------------*/

    @Builder
    public Inquiry(
            String responseId,
            LocalDateTime createdAt,
            String input,
            String prompt,
            String searchResult
    ) {
        this.responseId = responseId;
        this.createdAt = createdAt;
        this.input = input;
        this.prompt = prompt;
        this.searchResult = searchResult;
    }

/*-------------------- Methods --------------------*/

    public void update(
            String input,
            String prompt,
            String searchResult
    ) {
        this.input = input;
        this.prompt = prompt;
        this.searchResult = searchResult;
    }
}
