package com.osolar.obot.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.osolar.obot.config.DynamoDBConfig.LocalDateTimeConverter;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "response")
public class Response {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "bySessionId")
    private String sessionId;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    private String output;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
    private Boolean isSatisfied;

    @DynamoDBAttribute
    private String satisfactionReason;

/*-------------------- Constructors --------------------*/

    @Builder
    public Response(
            String sessionId,
            LocalDateTime createdAt,
            String output,
            Boolean isSatisfied,
            String satisfactionReason
    ) {
        this.sessionId = sessionId;
        this.createdAt = createdAt;
        this.output = output;
        this.isSatisfied = isSatisfied;
        this.satisfactionReason = satisfactionReason;
    }

/*-------------------- Methods --------------------*/

    public void update(
            String output,
            Boolean isSatisfied,
            String satisfactionReason
    ) {
        this.output = output;
        this.isSatisfied = isSatisfied;
        this.satisfactionReason = satisfactionReason;
    }
}
