package com.osolar.obot.domain.inquiry.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.osolar.obot.common.config.DynamoDBConfig;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@DynamoDBTable(tableName = "inquiry")
public class Inquiry {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "bySessionId")
    private String sessionId;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDBConfig.LocalDateTimeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
    private Boolean isSatisfied;

    @DynamoDBAttribute
    private String satisfactionReason;

/*-------------------- Constructors --------------------*/

    public Inquiry() {}

    @Builder
    public Inquiry(
            String sessionId,
            LocalDateTime createdAt,
            Boolean isSatisfied,
            String satisfactionReason
    ) {
        this.sessionId = sessionId;
        this.createdAt = createdAt;
        this.isSatisfied = isSatisfied;
        this.satisfactionReason = satisfactionReason;
    }

/*-------------------- Methods --------------------*/

}
