package com.osolar.obot.domain.user.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.osolar.obot.common.config.DynamoDBConfig.LocalDateTimeConverter;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@DynamoDBTable(tableName = "session")
public class UserSession {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "byUserId")
    private String userId;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private SessionStatus sessionStatus;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime updatedAt;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime endedAt;

/*-------------------- Constructors --------------------*/

    public UserSession() {}

    @Builder
    public UserSession(
            String userId,
            SessionStatus sessionStatus,
            LocalDateTime createdAt,
            LocalDateTime updatedAt,
            LocalDateTime endedAt
    ) {
        this.userId = userId;
        this.sessionStatus = sessionStatus;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.endedAt = endedAt;
    }

/*-------------------- Methods --------------------*/

    public void update(
            SessionStatus sessionStatus,
            LocalDateTime updatedAt,
            LocalDateTime endedAt
    ) {
        this.sessionStatus = sessionStatus;
        this.updatedAt = updatedAt;
        this.endedAt = endedAt;
    }
}
