package com.osolar.obot.domain.user.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "user")
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "byUsername")
    private String username;

    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    private String role;

/*-------------------- Constructors --------------------*/

    public User() {}

    @Builder
    public User(
            String username,
            String password,
            String role
    ) {
        this.username = username;
        this.password = password;
        this.role = role;
    }

/*-------------------- Methods --------------------*/

}
